// Facts about the current architecture that can't be derived live (unlike
// the rest of /status, which reads package.json/DATABASE_URL/Prisma
// directly). Keep this short — only update it when something at this level
// actually changes (a new data source, an auth system landing, another
// engine swap), not for every feature. See CLAUDE.md.
export const STATUS_NOTES: string[] = [
  "MySQL 8.4 LTS, not Postgres — targeting Oracle HeatWave's Always Free tier (MySQL.Free shape) as the eventual host. Pinned to 8.4 specifically (not the floating \"8\" tag) since Oracle stopped allowing new MySQL 8.0 DB Systems as of April 2026 and recommends 8.4 LTS for anything created from here on.",
  "No app-level authentication yet — the Galaxy API token lives in memory only (GameStatsAuthProvider, app/providers/), cleared on every page reload by design.",
  "Two parallel data sources: /matches (DB-backed, default, no token needed) and /galaxy/matches (live Galaxy fetch, requires a pasted token, has the manual per-row Sync button).",
  "Deployable to Vercel as a read-only viewer: writes stay off by default (isGalaxyEnabled() in lib/galaxyGate.ts requires both DATABASE_URL present and ENABLE_WRITE_MODE=true, unset/anything-else disables it) — proxy.ts's gate 404s every Galaxy/write route and the home page hides the Galaxy link when off. A temporary stopgap until a real auth wall exists. See docs/deploy.md.",
  "Decision notes (DecisionNote) are the app's first user-authored data — everything else is ingested from Galaxy or derived from it — and POST /api/decisions/[id]/note is its first write path outside sync/ingest. Same write gate (proxy.ts, isGalaxyEnabled()): editable only with write mode on, shown read-only otherwise. Notes are written to whichever DB DATABASE_URL points at; scripts/notes-export.ts / notes-import.ts move them between DBs by natural key, since Decision ids differ between local and Oracle.",
  "Spaced-repetition review (/review, /review/cards): ReviewCard (an FSRS schedule per studied decision, via ts-fsrs), ReviewLog (one row per answer), Tag and DecisionTag are user-authored data like DecisionNote. Cards store no position data: everything they show is derived from raw through lib/analysis/index.ts. Writes (/api/review/*, /api/tags/*) are behind the same write gate; the live site shows cards read-only.",
  "Externally-sourced string identifier columns (Match.sourceMatchId, PlayerIdentity.sourceUserId, Decision.userId, Decision.sourcePositionId, RepeatedPosition.sourcePositionId) are pinned to a case-sensitive/binary collation by hand-editing migration SQL — see docs/field-mapping.md.",
  "Columns earn their place: Decision stores only what SQL filters, sorts, groups or counts by, plus raw (Galaxy's untouched event). Everything else a decision shows — colour, roll and cube (from its GNU Match ID), labels, notations, the engine analysis — is derived from raw on demand through a per-source reader (lib/analysis/index.ts), so a future source (e.g. XG) plugs in there. See docs/field-mapping.md, \"Derived from raw\".",
];
